name: kulolesaa
description: Esperiencias de africa
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  cool_alert: ^2.0.1
  image_picker: ^0.8.6+1
  image_network: ^2.5.1
  timer_snackbar: ^0.0.3
  url_launcher: ^6.1.9
  date_time_picker: ^2.1.0
  favorite_button: ^0.0.4
  cached_network_image: ^3.2.3
  get: ^4.6.5
  shared_preferences: ^2.0.17
  flutter_phone_direct_caller: ^2.1.1
  material_floating_search_bar: ^0.3.7
  rive: ^0.10.3
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.2.19
  firebase_core: ^2.15.0
  firebase_database: ^10.2.2
  firebase_auth: ^4.6.2
  introduction_screen: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - acom/
  fonts:
    - family: roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: pp1
      fonts:
        - asset: fonts/pp1.ttf

    - family: pp2
      fonts:
        - asset: fonts/pp_reg.ttf

    - family: lilita
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf

    - family: direito
      fonts:
        - asset: fonts/Righteous-Regular.ttf

    - family: pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

flutter_native_splash:
  image: assets/images/splash.png
  color: "#ffffff"
  resize: contain
  fill: true
  android: true
  ios: true
